//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurcovaaGolovin.DataBaseControler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Childbirth
    {
        public int IDInpatient { get; set; }
        public int IDKid { get; set; }
        public System.DateTime StartChildbirth { get; set; }
        public System.DateTime EndChildbirth { get; set; }
        public string Description { get; set; }
        public string Birth_Place { get; set; }
        public string Birth_Type { get; set; }
        public string Operational_manuals { get; set; }
        public string StartChildbirthTime { get; set; }
        public string EndChildbirthTime { get; set; }
    
        public virtual Inpatient Inpatient { get; set; }
        public virtual Kid Kid { get; set; }
    }
}
