//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurcovaaGolovin.DataBaseControler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inpatient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inpatient()
        {
            this.Placement = new HashSet<Placement>();
        }
    
        public int IDInpatient { get; set; }
        public int IDWomanInLabor { get; set; }
        public System.DateTime StartInpatient { get; set; }
        public System.DateTime EndInpatient { get; set; }
        public string Description { get; set; }
        public int IDDoctor { get; set; }
    
        public virtual Childbirth Childbirth { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual WomanInLabor WomanInLabor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Placement> Placement { get; set; }
    }
}
