//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurcovaaGolovin.DataBaseControler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kid
    {
        public int IDKid { get; set; }
        public string NameKid { get; set; }
        public string SurnameKid { get; set; }
        public string MiddleNameKid { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public double Height { get; set; }
        public double Weight { get; set; }
        public int IDInpatient { get; set; }
        public Nullable<System.DateTime> DateofDischarge { get; set; }
        public string Locality { get; set; }
    
        public virtual Childbirth Childbirth { get; set; }
    }
}
