//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurcovaaGolovin.DataBaseControler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CurcovaaOBEntities6 : DbContext
    {
        public CurcovaaOBEntities6()
            : base("name=CurcovaaOBEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Childbirth> Childbirth { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Inpatient> Inpatient { get; set; }
        public virtual DbSet<Kid> Kid { get; set; }
        public virtual DbSet<Placement> Placement { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Ward> Ward { get; set; }
        public virtual DbSet<WomanInLabor> WomanInLabor { get; set; }
    }
}
