//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurcovaaGolovin.DataBaseControler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placement
    {
        public int IDPlacement { get; set; }
        public int IDInpatient { get; set; }
        public int NumberWard { get; set; }
        public System.DateTime DatePlacement { get; set; }
        public Nullable<System.DateTime> DateOfTransfer { get; set; }
    
        public virtual Inpatient Inpatient { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
