//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurcovaaGolovin.DataBaseControler
{
    using System;
    using System.Collections.Generic;
    
    public partial class WomanInLabor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WomanInLabor()
        {
            this.Inpatient = new HashSet<Inpatient>();
        }
    
        public int IDWomanInLabor { get; set; }
        public string NameWomanInLabor { get; set; }
        public string SurnameWomanInLabor { get; set; }
        public string MiddleNameWomanInLabor { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public string PhoneWomanInLabor { get; set; }
        public string SpecialMarks { get; set; }
        public string WomanAge { get; set; }
        public string Post_birth_time { get; set; }
        public Nullable<int> Gestation_Count { get; set; }
        public Nullable<int> Gestation_Period { get; set; }
        public string Family_State { get; set; }
        public string Locality { get; set; }
        public Nullable<System.DateTime> DateofDischarge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inpatient> Inpatient { get; set; }
    }
}
